-- Export de la base de données dccdb
-- Généré le 2026-01-29T07:08:06.214Z
-- Ne pas modifier à la main.

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";


-- Table: dataset_versions
DROP TABLE IF EXISTS `dataset_versions`;
CREATE TABLE `dataset_versions` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `effectiveAt` timestamp(6) NOT NULL,
  `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `dataset_versions_version_key` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for table dataset_versions
INSERT INTO `dataset_versions` (`id`, `version`, `description`, `effectiveAt`, `createdAt`) VALUES ('8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'v1', 'Initial DCC dataset (1A, 1B, 1C)', '2026-01-27 08:08:57', '2026-01-27 08:08:57');

-- Table: income_plans
DROP TABLE IF EXISTS `income_plans`;
CREATE TABLE `income_plans` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `loanAmount` decimal(20,2) NOT NULL,
  `currency` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `riskTolerance` int NOT NULL,
  `ltv` decimal(5,2) NOT NULL,
  `collateralUSD` decimal(20,2) NOT NULL,
  `collateralBTC` decimal(20,8) NOT NULL,
  `bitcoinPrice` decimal(20,2) NOT NULL,
  `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` timestamp(6) NOT NULL,
  `incomeObjective` decimal(20,2) DEFAULT NULL,
  `userId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: instrument_snapshots
DROP TABLE IF EXISTS `instrument_snapshots`;
CREATE TABLE `instrument_snapshots` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `instrumentId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `asOf` timestamp(6) NOT NULL,
  `apyMin` decimal(10,4) DEFAULT NULL,
  `apyMax` decimal(10,4) DEFAULT NULL,
  `rateType` enum('Fixed','Variable','QuoteBased','Promo','Unknown') COLLATE utf8mb4_unicode_ci NOT NULL,
  `apyLabelOverride` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `promoFlag` tinyint(1) NOT NULL DEFAULT '0',
  `sourceUrl` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `instrument_snapshots_instrumentId_idx` (`instrumentId`),
  CONSTRAINT `instrument_snapshots_instrumentId_fkey` FOREIGN KEY (`instrumentId`) REFERENCES `instruments` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: instruments
DROP TABLE IF EXISTS `instruments`;
CREATE TABLE `instruments` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `module` enum('M1A','M1B','M1C') COLLATE utf8mb4_unicode_ci NOT NULL,
  `datasetVersionId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issuer` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `productName` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL,
  `collateral` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `jurisdiction` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lockup` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `seniority` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `notes` text COLLATE utf8mb4_unicode_ci,
  `sources` json DEFAULT NULL,
  `apyLabel` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `promoFlag` tinyint(1) NOT NULL DEFAULT '0',
  `unverifiableReason` text COLLATE utf8mb4_unicode_ci,
  `internalSources` json DEFAULT NULL,
  `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` timestamp(6) NOT NULL,
  `ltvTypical` decimal(5,2) DEFAULT NULL,
  `marginCallLtv` decimal(5,2) DEFAULT NULL,
  `liquidationLtv` decimal(5,2) DEFAULT NULL,
  `liquidationPenalty` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rehypothecationPolicy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contractingEntity` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `governingLaw` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `regionEligibility` json DEFAULT NULL,
  `minLoanSize` decimal(20,2) DEFAULT NULL,
  `accreditedOnly` tinyint(1) DEFAULT '0',
  `feeOrigination` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `feeAdmin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `feeSpread` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cusip` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isin` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dividendRate` decimal(10,4) DEFAULT NULL,
  `paymentFrequency` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `coupon` decimal(10,4) DEFAULT NULL,
  `maturity` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `conversionTriggers` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isYield` tinyint(1) DEFAULT '1',
  `secYield` decimal(10,4) DEFAULT NULL,
  `trailingDistributionRate` decimal(10,4) DEFAULT NULL,
  `venueType` enum('DeFi','CeFi','RWA') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supportedAsset` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `chain` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `userTier` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `noticePeriod` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `redemptionGates` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dailyLimit` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `riskTags` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `instruments_datasetVersionId_fkey` (`datasetVersionId`),
  CONSTRAINT `instruments_datasetVersionId_fkey` FOREIGN KEY (`datasetVersionId`) REFERENCES `dataset_versions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for table instruments
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('001f46cc-96cb-4113-87ba-cc3f107fd0f5', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Julius Baer', 'Crypto-backed Lombard Credit', 'BTC/crypto', 'Switzerland / Global', 'Bespoke', 'Secured', 'Case-by-case private banking facility.', 'https://www.juliusbaer.com/', 'Quote-based (Borrow cost)', 'Bespoke', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('02bdcb3f-f257-4fee-9aac-67cb6f16ef5e', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Dukascopy Bank', 'Crypto Collateral Lending', 'BTC/crypto', 'Switzerland', 'Unknown', 'Secured', 'Verify liquidation mechanics per agreement.', 'https://www.dukascopy.com/swiss/english/crypto/', 'Quote-based (Borrow cost)', 'Unknown', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('0bdb1875-51bf-45c7-9e43-8146943e7c71', 'M1B', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Strategy Inc.', 'STRK Preferred', 'Unsecured', 'US', 'Market', 'Preferred equity', 'Dividend not guaranteed.', 'https://www.strategy.com', '8.0% Fixed (when declared)', 'Perpetual', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Quarterly', NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('20cec258-c634-44a4-b43d-6b1a0649945e', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Ledn', 'Bitcoin‑Backed Loans', 'BTC', 'Canada', 'Termed', 'Secured', 'Typical 50% LTV; confirm liquidation thresholds and custody structure.', 'https://ledn.io/en/bitcoin-backed-loans', '11.9% APR (borrow cost)', 'Termed', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', '50.00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('27dc195b-ff33-422d-8306-518bab1263d5', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Aave (DeFi)', 'Borrow USDC against WBTC (Aave v3)', 'WBTC', 'On‑chain', 'None', 'Protocol claim', 'Smart‑contract, oracle and WBTC custodian risk apply.', 'https://app.aave.com/', 'Variable (market‑driven)', 'On‑demand', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('2934d846-47b8-4f5b-90d0-4a04a994c323', 'M1C', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Aave', 'Supply USDC', 'Overcollateralized pool', 'On-chain', 'None', 'Protocol claim', 'Utilization-dependent.', 'https://app.aave.com', 'Variable', 'On-demand', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'DeFi', 'USDC', 'Ethereum', NULL, 'None', NULL, NULL, 'smart-contract,oracle');
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('2ba85532-ae35-4598-9ea6-a2ecbaea9caa', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Sats Terminal', 'BTC Yield & Structured Products Marketplace', 'BTC (partner‑dependent)', 'Global (structure‑dependent)', 'Varies', 'Structure‑dependent', 'Acts as distribution & analytics layer; verify underlying counterparty.', 'https://satsterminal.com/', 'Product‑specific / variable', 'Varies by instrument', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('2cd80ef7-af3d-4dba-ac05-c9b5f2c9c8a9', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'SALT Lending', 'Crypto‑Backed Loans', 'BTC & supported crypto', 'USA', 'Termed', 'Secured', 'APR varies by LTV; liquidation rules must be confirmed in loan docs.', 'https://saltlending.com', '9.95–14.45% APR', 'Up to 12 months', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('353d3d21-b26f-4b3d-92df-3105f0b429f6', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Unchained Capital', 'Bitcoin‑Backed Loans (Multi‑Sig)', 'BTC (2‑of‑3 multisig)', 'USA', 'Termed', 'Secured', 'Client retains one key; confirm fees, margin calls and liquidation logic.', 'https://unchained.com/loans', 'Not publicly disclosed', '90–360 days', 0, 'Rates not publicly disclosed; application required.', NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('416ef782-bfa4-4c9f-8314-8d32dd9c25fc', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Abra', 'Bitcoin‑Backed Loans (Abra Borrow)', 'BTC collateral', 'USA (entity‑dependent)', 'Termed', 'Secured', 'Availability varies by jurisdiction; confirm current program status.', 'https://www.abra.com/', 'Historically ~3–8% APR (not guaranteed)', 'Termed / flexible', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('431551bd-28fe-4570-aa40-7ce9b7a73e95', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Mezo × Anchorage Digital', 'MUSD BTC‑Collateralized Borrowing', 'BTC (110% collateral stated)', 'USA', 'Unknown', 'Secured', 'Institutional‑grade custody; eligibility likely Anchorage‑client only.', 'https://www.anchorage.com/blog/mezo-and-anchorage-digital-launch-btc-collateralized-lending-and-borrowing', 'From ~1% APR (fixed)', 'Not disclosed', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('5f0d6dfc-1b01-48b6-a16e-ff6341cac766', 'M1B', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Metaplanet Inc.', 'BTC-backed Borrowings', 'BTC', 'Japan', 'Termed', 'Secured', 'BTC used as collateral; no public rates.', 'https://metaplanet.jp', 'Unknown', 'Termed', 0, 'No public rates disclosed.', NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('6e352271-c209-4b87-bad5-1d45335ee0e7', 'M1C', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Maple Finance', 'Cash Management Pool', 'RWA (T-bills)', 'On-chain', '~24h', 'Protocol/vehicle claim', 'Eligibility applies.', 'https://maple.finance', 'Variable', 'On-demand', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'RWA', 'USDC', NULL, NULL, '24 hours', NULL, NULL, 'counterparty,liquidity');
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('7d9772ce-63c7-4c5c-907f-f9ba4bfda65e', 'M1B', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Metaplanet Inc.', 'Zero-Coupon Bonds', 'Unsecured', 'Japan', 'Secondary', 'Senior unsecured', 'Issued to acquire BTC.', 'https://metaplanet.jp', '0%', 'Dated', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0.0000', NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('82b3ad76-a471-4126-bd24-b6a8af514a7c', 'M1C', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'MakerDAO / Spark', 'DAI Savings Rate', 'Protocol reserves', 'On-chain', 'None', 'Protocol claim', 'Governance-set rate.', 'https://spark.fi', 'Variable', 'On-demand', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'DeFi', 'DAI', NULL, NULL, 'None', NULL, NULL, 'peg,smart-contract');
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('a68abc95-921c-4a35-ba66-e21572e803c8', 'M1C', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Binance', 'Simple Earn USDC', 'Unsecured', 'Global', 'Flexible', 'Unsecured', 'Promo tiers apply.', 'https://www.binance.com', 'Promo / Variable', 'Flexible', 1, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'CeFi', 'USDC', NULL, NULL, 'None', NULL, NULL, 'counterparty,promo');
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('ab89b68e-6bc1-4371-8182-f5b9e1665365', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Sygnum Bank', 'Crypto Lombard Loan', 'BTC', 'Switzerland', 'Termed', 'Secured', 'Explicit BTC Lombard lending.', 'https://www.sygnum.com/products/credit/', 'Quote-based (Borrow cost)', 'Termed / revolving', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('bd5e747e-b58c-418d-b400-ea17f1d989c5', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'AMINA Bank', 'Crypto-Backed Loans', 'BTC', 'Switzerland', 'Termed', 'Secured', 'Regulated crypto bank offering BTC-backed loans.', 'https://aminagroup.com/products/crypto-backed-loans/', 'Quote-based (Borrow cost)', 'Termed / revolving', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('db316606-97d5-46d2-8637-6fe3636d08d3', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Arch Lending', 'Bitcoin & Crypto Loans', 'BTC / ETH / SOL', 'USA', 'Unknown', 'Secured', 'Rates visible only post‑application; suitable for calculator ingestion.', 'https://archlending.com/', 'Not disclosed', 'Not disclosed', 0, 'Rates visible only post‑application.', NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('db4bb47d-899e-4df0-82df-63a5ba702610', 'M1A', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Galaxy Digital', 'Institutional Lending Desk', 'Crypto collateral', 'USA / Global', 'Deal‑specific', 'Contractual', 'Institutional desk; requires per‑deal term sheet ingestion.', 'https://www.galaxy.com/services/lending/', 'Quote‑based', 'Bespoke', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `instruments` (`id`, `module`, `datasetVersionId`, `issuer`, `productName`, `collateral`, `jurisdiction`, `lockup`, `seniority`, `notes`, `sources`, `apyLabel`, `duration`, `promoFlag`, `unverifiableReason`, `internalSources`, `createdAt`, `updatedAt`, `ltvTypical`, `marginCallLtv`, `liquidationLtv`, `liquidationPenalty`, `rehypothecationPolicy`, `contractingEntity`, `governingLaw`, `regionEligibility`, `minLoanSize`, `accreditedOnly`, `feeOrigination`, `feeAdmin`, `feeSpread`, `cusip`, `isin`, `dividendRate`, `paymentFrequency`, `coupon`, `maturity`, `conversionTriggers`, `isYield`, `secYield`, `trailingDistributionRate`, `venueType`, `supportedAsset`, `chain`, `userTier`, `noticePeriod`, `redemptionGates`, `dailyLimit`, `riskTags`) VALUES ('e68b816f-a11e-45ff-88ad-14dad2667584', 'M1C', '8fdd133b-c37f-48c5-a87b-5105e3e2026b', 'Coinbase', 'USDC Rewards', 'Unsecured', 'US', 'None', 'Unsecured', 'Program-based rewards.', 'https://www.coinbase.com', 'Variable', 'On-demand', 0, NULL, NULL, '2026-01-27 08:08:57', '2026-01-27 08:08:57', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, 'CeFi', 'USDC', NULL, NULL, 'None', NULL, NULL, 'counterparty');

-- Table: suitability_reports
DROP TABLE IF EXISTS `suitability_reports`;
CREATE TABLE `suitability_reports` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `incomePlanId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `datasetVersionId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reportType` enum('Suitability','Income','Risk') COLLATE utf8mb4_unicode_ci NOT NULL,
  `frozenData` json NOT NULL,
  `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `suitability_reports_datasetVersionId_fkey` (`datasetVersionId`),
  KEY `suitability_reports_incomePlanId_fkey` (`incomePlanId`),
  CONSTRAINT `suitability_reports_datasetVersionId_fkey` FOREIGN KEY (`datasetVersionId`) REFERENCES `dataset_versions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `suitability_reports_incomePlanId_fkey` FOREIGN KEY (`incomePlanId`) REFERENCES `income_plans` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: users
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `emailVerified` tinyint(1) NOT NULL DEFAULT '0',
  `verificationToken` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verificationTokenExpires` timestamp(6) NULL DEFAULT NULL,
  `createdAt` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` timestamp(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_key` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data for table users
INSERT INTO `users` (`id`, `name`, `email`, `password`, `emailVerified`, `verificationToken`, `verificationTokenExpires`, `createdAt`, `updatedAt`) VALUES ('d00c2f1a-8957-4c7d-8706-5c4e640eb651', 'Henri-Mill FETCHOUANG', 'xtvalizo@gmail.com', '$2b$10$BbRwfuV7UiH0qyHF3MFiSeIth73InvlgRcmVaXkHE1Nb3Hm8VV6SG', 0, '2d793d1a020a10a49305f0b7df3e6670069bff78f5e48001d4e3ca4630cbed7a', '2026-01-29 06:18:08', '2026-01-28 06:18:08', '2026-01-28 06:18:08');

SET FOREIGN_KEY_CHECKS=1;
