require('dotenv/config')
const { PrismaClient, Prisma, DccModule, RateType, VenueType } = require('@prisma/client')

const prisma = new PrismaClient()

const d = (n) => new Prisma.Decimal(n)

function src(url) {
  return url ? [url] : null
}

async function main() {
  const now = new Date()

  const v1 = await prisma.datasetVersion.upsert({
    where: { version: 'v1' },
    update: {},
    create: {
      version: 'v1',
      description: 'Initial DCC dataset (1A, 1B, 1C)',
      effectiveAt: now,
    },
  })

  // ---------- 1A: BTC Income Planner (BTC-backed borrowing) ----------
  const m1a = [
    {
      issuer: 'Ledn',
      productName: 'Bitcoin‑Backed Loans',
      apyLabel: '11.9% APR (borrow cost)',
      duration: 'Termed',
      collateral: 'BTC',
      jurisdiction: 'Canada',
      lockup: 'Termed',
      seniority: 'Secured',
      notes: 'Typical 50% LTV; confirm liquidation thresholds and custody structure.',
      sources: src('https://ledn.io/en/bitcoin-backed-loans'),
      apyMin: 11.9,
      apyMax: 11.9,
      rateType: RateType.Fixed,
      ltvTypical: 50,
    },
    {
      issuer: 'Unchained Capital',
      productName: 'Bitcoin‑Backed Loans (Multi‑Sig)',
      apyLabel: 'Not publicly disclosed',
      duration: '90–360 days',
      collateral: 'BTC (2‑of‑3 multisig)',
      jurisdiction: 'USA',
      lockup: 'Termed',
      seniority: 'Secured',
      notes: 'Client retains one key; confirm fees, margin calls and liquidation logic.',
      sources: src('https://unchained.com/loans'),
      rateType: RateType.Unknown,
      unverifiableReason: 'Rates not publicly disclosed; application required.',
    },
    {
      issuer: 'SALT Lending',
      productName: 'Crypto‑Backed Loans',
      apyLabel: '9.95–14.45% APR',
      duration: 'Up to 12 months',
      collateral: 'BTC & supported crypto',
      jurisdiction: 'USA',
      lockup: 'Termed',
      seniority: 'Secured',
      notes: 'APR varies by LTV; liquidation rules must be confirmed in loan docs.',
      sources: src('https://saltlending.com'),
      apyMin: 9.95,
      apyMax: 14.45,
      rateType: RateType.Variable,
    },
    {
      issuer: 'Mezo × Anchorage Digital',
      productName: 'MUSD BTC‑Collateralized Borrowing',
      apyLabel: 'From ~1% APR (fixed)',
      duration: 'Not disclosed',
      collateral: 'BTC (110% collateral stated)',
      jurisdiction: 'USA',
      lockup: 'Unknown',
      seniority: 'Secured',
      notes: 'Institutional‑grade custody; eligibility likely Anchorage‑client only.',
      sources: src('https://www.anchorage.com/blog/mezo-and-anchorage-digital-launch-btc-collateralized-lending-and-borrowing'),
      apyMin: 1,
      apyMax: null,
      rateType: RateType.Fixed,
    },
    {
      issuer: 'Galaxy Digital',
      productName: 'Institutional Lending Desk',
      apyLabel: 'Quote‑based',
      duration: 'Bespoke',
      collateral: 'Crypto collateral',
      jurisdiction: 'USA / Global',
      lockup: 'Deal‑specific',
      seniority: 'Contractual',
      notes: 'Institutional desk; requires per‑deal term sheet ingestion.',
      sources: src('https://www.galaxy.com/services/lending/'),
      rateType: RateType.QuoteBased,
    },
    {
      issuer: 'Arch Lending',
      productName: 'Bitcoin & Crypto Loans',
      apyLabel: 'Not disclosed',
      duration: 'Not disclosed',
      collateral: 'BTC / ETH / SOL',
      jurisdiction: 'USA',
      lockup: 'Unknown',
      seniority: 'Secured',
      notes: 'Rates visible only post‑application; suitable for calculator ingestion.',
      sources: src('https://archlending.com/'),
      rateType: RateType.Unknown,
      unverifiableReason: 'Rates visible only post‑application.',
    },
    {
      issuer: 'Abra',
      productName: 'Bitcoin‑Backed Loans (Abra Borrow)',
      apyLabel: 'Historically ~3–8% APR (not guaranteed)',
      duration: 'Termed / flexible',
      collateral: 'BTC collateral',
      jurisdiction: 'USA (entity‑dependent)',
      lockup: 'Termed',
      seniority: 'Secured',
      notes: 'Availability varies by jurisdiction; confirm current program status.',
      sources: src('https://www.abra.com/'),
      apyMin: 3,
      apyMax: 8,
      rateType: RateType.Variable,
    },
    {
      issuer: 'Sats Terminal',
      productName: 'BTC Yield & Structured Products Marketplace',
      apyLabel: 'Product‑specific / variable',
      duration: 'Varies by instrument',
      collateral: 'BTC (partner‑dependent)',
      jurisdiction: 'Global (structure‑dependent)',
      lockup: 'Varies',
      seniority: 'Structure‑dependent',
      notes: 'Acts as distribution & analytics layer; verify underlying counterparty.',
      sources: src('https://satsterminal.com/'),
      rateType: RateType.Variable,
    },
    {
      issuer: 'Aave (DeFi)',
      productName: 'Borrow USDC against WBTC (Aave v3)',
      apyLabel: 'Variable (market‑driven)',
      duration: 'On‑demand',
      collateral: 'WBTC',
      jurisdiction: 'On‑chain',
      lockup: 'None',
      seniority: 'Protocol claim',
      notes: 'Smart‑contract, oracle and WBTC custodian risk apply.',
      sources: src('https://app.aave.com/'),
      rateType: RateType.Variable,
    },
    {
      issuer: 'Sygnum Bank',
      productName: 'Crypto Lombard Loan',
      apyLabel: 'Quote-based (Borrow cost)',
      duration: 'Termed / revolving',
      collateral: 'BTC',
      jurisdiction: 'Switzerland',
      lockup: 'Termed',
      seniority: 'Secured',
      notes: 'Explicit BTC Lombard lending.',
      sources: src('https://www.sygnum.com/products/credit/'),
      rateType: RateType.QuoteBased,
    },
    {
      issuer: 'AMINA Bank',
      productName: 'Crypto-Backed Loans',
      apyLabel: 'Quote-based (Borrow cost)',
      duration: 'Termed / revolving',
      collateral: 'BTC',
      jurisdiction: 'Switzerland',
      lockup: 'Termed',
      seniority: 'Secured',
      notes: 'Regulated crypto bank offering BTC-backed loans.',
      sources: src('https://aminagroup.com/products/crypto-backed-loans/'),
      rateType: RateType.QuoteBased,
    },
    {
      issuer: 'Dukascopy Bank',
      productName: 'Crypto Collateral Lending',
      apyLabel: 'Quote-based (Borrow cost)',
      duration: 'Unknown',
      collateral: 'BTC/crypto',
      jurisdiction: 'Switzerland',
      lockup: 'Unknown',
      seniority: 'Secured',
      notes: 'Verify liquidation mechanics per agreement.',
      sources: src('https://www.dukascopy.com/swiss/english/crypto/'),
      rateType: RateType.QuoteBased,
    },
    {
      issuer: 'Julius Baer',
      productName: 'Crypto-backed Lombard Credit',
      apyLabel: 'Quote-based (Borrow cost)',
      duration: 'Bespoke',
      collateral: 'BTC/crypto',
      jurisdiction: 'Switzerland / Global',
      lockup: 'Bespoke',
      seniority: 'Secured',
      notes: 'Case-by-case private banking facility.',
      sources: src('https://www.juliusbaer.com/'),
      rateType: RateType.QuoteBased,
    },
  ]

  for (const row of m1a) {
    const { apyMin, apyMax, rateType, ltvTypical, unverifiableReason, ...rest } = row
    const inst = await prisma.instrument.create({
      data: {
        module: DccModule.M1A,
        datasetVersionId: v1.id,
        ...rest,
        ltvTypical: ltvTypical != null ? d(ltvTypical) : undefined,
        unverifiableReason: unverifiableReason || undefined,
      },
    })
    await prisma.instrumentSnapshot.create({
      data: {
        instrumentId: inst.id,
        asOf: now,
        apyMin: apyMin != null ? d(apyMin) : undefined,
        apyMax: apyMax != null ? d(apyMax) : undefined,
        rateType,
      },
    })
  }

  // ---------- 1B: Fiat Income Planner (digital credit) ----------
  const m1b = [
    {
      issuer: 'Strategy Inc.',
      productName: 'STRK Preferred',
      apyLabel: '8.0% Fixed (when declared)',
      duration: 'Perpetual',
      collateral: 'Unsecured',
      jurisdiction: 'US',
      lockup: 'Market',
      seniority: 'Preferred equity',
      notes: 'Dividend not guaranteed.',
      sources: src('https://www.strategy.com'),
      apyMin: 8,
      apyMax: 8,
      rateType: RateType.Fixed,
      paymentFrequency: 'Quarterly',
      isYield: true,
    },
    {
      issuer: 'Strategy Inc.',
      productName: 'STRC Preferred',
      apyLabel: 'Variable (monthly reset)',
      duration: 'Perpetual',
      collateral: 'Unsecured',
      jurisdiction: 'US',
      lockup: 'Market',
      seniority: 'Preferred equity',
      notes: 'Rate adjusts monthly.',
      sources: src('https://www.strategy.com'),
      apyMin: 4,
      apyMax: 7,
      rateType: RateType.Variable,
      paymentFrequency: 'Quarterly',
      isYield: true,
    },
    {
      issuer: 'Strategy Inc.',
      productName: 'STRE Preferred',
      apyLabel: '10.0% (per terms)',
      duration: 'Perpetual',
      collateral: 'Unsecured',
      jurisdiction: 'US / EU',
      lockup: 'Market',
      seniority: 'Preferred equity',
      notes: 'Confirm ranking among series.',
      sources: src('https://www.strategy.com'),
      apyMin: 10,
      apyMax: 10,
      rateType: RateType.Fixed,
      paymentFrequency: 'Quarterly',
      isYield: true,
    },
    {
      issuer: 'Strategy Inc.',
      productName: 'Convertible Notes',
      apyLabel: '0% coupon',
      duration: 'Dated',
      collateral: 'Unsecured',
      jurisdiction: 'US',
      lockup: 'Secondary',
      seniority: 'Senior unsecured',
      notes: 'Digital credit, not yield.',
      sources: src('https://www.strategy.com'),
      apyMin: 0,
      apyMax: 0,
      rateType: RateType.Fixed,
      coupon: 0,
      isYield: false,
    },
    {
      issuer: 'Metaplanet Inc.',
      productName: 'Zero-Coupon Bonds',
      apyLabel: '0%',
      duration: 'Dated',
      collateral: 'Unsecured',
      jurisdiction: 'Japan',
      lockup: 'Secondary',
      seniority: 'Senior unsecured',
      notes: 'Issued to acquire BTC.',
      sources: src('https://metaplanet.jp'),
      apyMin: 0,
      apyMax: 0,
      rateType: RateType.Fixed,
      coupon: 0,
      isYield: false,
    },
    {
      issuer: 'Metaplanet Inc.',
      productName: 'BTC-backed Borrowings',
      apyLabel: 'Unknown',
      duration: 'Termed',
      collateral: 'BTC',
      jurisdiction: 'Japan',
      lockup: 'Termed',
      seniority: 'Secured',
      notes: 'BTC used as collateral; no public rates.',
      sources: src('https://metaplanet.jp'),
      rateType: RateType.Unknown,
      unverifiableReason: 'No public rates disclosed.',
    },
  ]

  for (const row of m1b) {
    const { apyMin, apyMax, rateType, paymentFrequency, coupon, isYield, unverifiableReason, ...rest } = row
    const inst = await prisma.instrument.create({
      data: {
        module: DccModule.M1B,
        datasetVersionId: v1.id,
        ...rest,
        paymentFrequency: paymentFrequency || undefined,
        coupon: coupon != null ? d(coupon) : undefined,
        isYield: isYield ?? true,
        unverifiableReason: unverifiableReason || undefined,
      },
    })
    await prisma.instrumentSnapshot.create({
      data: {
        instrumentId: inst.id,
        asOf: now,
        apyMin: apyMin != null ? d(apyMin) : undefined,
        apyMax: apyMax != null ? d(apyMax) : undefined,
        rateType,
      },
    })
  }

  // ---------- 1C: Stablecoin Income Planner ----------
  const m1c = [
    {
      issuer: 'MakerDAO / Spark',
      productName: 'DAI Savings Rate',
      apyLabel: 'Variable',
      duration: 'On-demand',
      collateral: 'Protocol reserves',
      jurisdiction: 'On-chain',
      lockup: 'None',
      seniority: 'Protocol claim',
      notes: 'Governance-set rate.',
      sources: src('https://spark.fi'),
      apyMin: 3,
      apyMax: 6,
      rateType: RateType.Variable,
      venueType: VenueType.DeFi,
      supportedAsset: 'DAI',
      noticePeriod: 'None',
      riskTags: ['peg', 'smart-contract'],
    },
    {
      issuer: 'Aave',
      productName: 'Supply USDC',
      apyLabel: 'Variable',
      duration: 'On-demand',
      collateral: 'Overcollateralized pool',
      jurisdiction: 'On-chain',
      lockup: 'None',
      seniority: 'Protocol claim',
      notes: 'Utilization-dependent.',
      sources: src('https://app.aave.com'),
      apyMin: 3.5,
      apyMax: 5.2,
      rateType: RateType.Variable,
      venueType: VenueType.DeFi,
      supportedAsset: 'USDC',
      chain: 'Ethereum',
      noticePeriod: 'None',
      riskTags: ['smart-contract', 'oracle'],
    },
    {
      issuer: 'Coinbase',
      productName: 'USDC Rewards',
      apyLabel: 'Variable',
      duration: 'On-demand',
      collateral: 'Unsecured',
      jurisdiction: 'US',
      lockup: 'None',
      seniority: 'Unsecured',
      notes: 'Program-based rewards.',
      sources: src('https://www.coinbase.com'),
      apyMin: 2,
      apyMax: 5,
      rateType: RateType.Variable,
      venueType: VenueType.CeFi,
      supportedAsset: 'USDC',
      noticePeriod: 'None',
      riskTags: ['counterparty'],
    },
    {
      issuer: 'Binance',
      productName: 'Simple Earn USDC',
      apyLabel: 'Promo / Variable',
      duration: 'Flexible',
      collateral: 'Unsecured',
      jurisdiction: 'Global',
      lockup: 'Flexible',
      seniority: 'Unsecured',
      notes: 'Promo tiers apply.',
      sources: src('https://www.binance.com'),
      apyMin: 4,
      apyMax: 6.5,
      rateType: RateType.Promo,
      promoFlag: true,
      venueType: VenueType.CeFi,
      supportedAsset: 'USDC',
      noticePeriod: 'None',
      riskTags: ['counterparty', 'promo'],
    },
    {
      issuer: 'Maple Finance',
      productName: 'Cash Management Pool',
      apyLabel: 'Variable',
      duration: 'On-demand',
      collateral: 'RWA (T-bills)',
      jurisdiction: 'On-chain',
      lockup: '~24h',
      seniority: 'Protocol/vehicle claim',
      notes: 'Eligibility applies.',
      sources: src('https://maple.finance'),
      apyMin: 5,
      apyMax: 7,
      rateType: RateType.Variable,
      venueType: VenueType.RWA,
      supportedAsset: 'USDC',
      noticePeriod: '24 hours',
      riskTags: ['counterparty', 'liquidity'],
    },
  ]

  for (const row of m1c) {
    const {
      apyMin,
      apyMax,
      rateType,
      promoFlag,
      venueType,
      supportedAsset,
      chain,
      noticePeriod,
      riskTags,
      ...rest
    } = row
    const inst = await prisma.instrument.create({
      data: {
        module: DccModule.M1C,
        datasetVersionId: v1.id,
        ...rest,
        promoFlag: !!promoFlag,
        venueType: venueType || undefined,
        supportedAsset: supportedAsset || undefined,
        chain: chain || undefined,
        noticePeriod: noticePeriod || undefined,
        riskTags: riskTags || undefined,
      },
    })
    await prisma.instrumentSnapshot.create({
      data: {
        instrumentId: inst.id,
        asOf: now,
        apyMin: apyMin != null ? d(apyMin) : undefined,
        apyMax: apyMax != null ? d(apyMax) : undefined,
        rateType,
        promoFlag: !!promoFlag,
      },
    })
  }

  console.log('Seed complete: DatasetVersion v1, 1A/1B/1C instruments + snapshots.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
